CNJewellerAdmin/Models/UserDetail.cs
using System;
using System.Collections.Generic;

namespace CNJewellerAdmin.Models
{
    public partial class UserDetail
    {
        public int Id { get; set; }
        public int OfficeId { get; set; }
        public string FirstName { get; set; } = null!;
        public string MiddleName { get; set; } = null!;
        public string LastName { get; set; } = null!;
        public string MobileNo { get; set; } = null!;
        public string? EmailId { get; set; }
        public string City { get; set; } = null!;
        public string Pincode { get; set; } = null!;
        public string Address { get; set; } = null!;
        public DateTime? JoiningDate { get; set; }
        public int RoleId { get; set; }
        public int UserType { get; set; }
        public int? Gender { get; set; }
        public string Password { get; set; } = null!;
        public string? ProfilePic { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int RowStatus { get; set; }

        public virtual OfficeMaster Office { get; set; } = null!;
    }
}

CNJewellerAdmin/Controllers/UserDetailsController.cs
using CNJewellerAdmin.DTOs.Base;
using CNJewellerAdmin.DTOs.UserDetails;
using CNJewellerAdmin.Helper;
using CNJewellerAdmin.Helper.DataAccess;
using CNJewellerAdmin.Helper.DateUtil;
using CNJewellerAdmin.Model;
using CNJewellerAdmin.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Common;
using NuGet.Protocol.Plugins;
using static Microsoft.AspNetCore.Razor.Language.TagHelperMetadata;

namespace CNJewellerAdmin.Controllers
{
    public class UserDetailsController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetUserList(int officeId)
        {
            List<UserDetailsDTO> result = new List<UserDetailsDTO>();
            try
            {
                using (var db = new CNJContext())
                {
                    var userDetails = db.UserDetails.Where(x => x.RowStatus != (int)RowStatus.Deleted);
                    var officeDetails = db.OfficeMasters.Where(x => x.RowStatus != (int)RowStatus.Deleted);
                    var userData = (from ud in userDetails
                                    join om in officeDetails on ud.OfficeId equals om.Id
                                    select new UserDetailsDTO
                                    {
                                        Id = ud.Id,
                                        OfficeId = ud.OfficeId,
                                        OfficeName = om.OfficeName,
                                        FirstName = ud.FirstName,
                                        MiddleName = ud.MiddleName,
                                        LastName = ud.LastName,
                                        MobileNo = ud.MobileNo,
                                        EmailId = ud.EmailId,
                                        City = ud.City,
                                        Pincode = ud.Pincode,
                                        Address = ud.Address,
                                        JoiningDate = DateUtil.GetDateString(ud.JoiningDate),
                                        RoleId = ud.RoleId,
                                        UserType = ud.UserType,
                                        Gender = ud.Gender,
                                        GenderName = ((Genders)ud.Gender).ToString(),
                                        ProfilePic = ud.ProfilePic,
                                        RowStatus = ud.RowStatus
                                    });

                    //if (request.OfficeId > 0)
                    //{
                    //    userData = userData.Where(x => x.OfficeId == request.OfficeId);
                    //}
                    result = userData.ToList();
                }
            }
            catch (Exception ex)
            {
            }
            return Json(result);
        }

        public async Task<IActionResult> OpenUserDetailsForm(int id)
        {
            BaseResponse response = new BaseResponse();
            CreateUpdateUserDetailRequest request = new CreateUpdateUserDetailRequest();
            request.Genders = new List<DropDownBase>();
            request.Roles = new List<DropDownBase>();
            request.Offices = new List<DropDownBase>();
            try
            {
                var genderList = ((Genders[])Enum.GetValues(typeof(Genders))).Select(c => new DropDownBase() { Id = (int)c, Name = c.ToString() }).ToList();
                request.Genders = genderList;
                using (var db = new CNJContext())
                {
                    request.Offices = await db.OfficeMasters.Where(x => x.RowStatus == (int)RowStatus.Active).Select(x => new DropDownBase
                    {
                        Id = x.Id,
                        Name = x.OfficeName
                    }).ToListAsync();

                    if (id > 0)
                    {
                        var getUserDetails = await db.UserDetails.FirstOrDefaultAsync(x => x.Id == id && x.RowStatus == (int)RowStatus.Active);
                        if (getUserDetails != null)
                        {
                            request.Id = getUserDetails.Id;
                            request.OfficeId = getUserDetails.OfficeId;
                            request.FirstName = getUserDetails.FirstName;
                            request.MiddleName = getUserDetails.MiddleName;
                            request.LastName = getUserDetails.LastName;
                            request.MobileNo = getUserDetails.MobileNo;
                            request.EmailId = getUserDetails.EmailId;
                            request.City = getUserDetails.City;
                            request.Pincode = getUserDetails.Pincode;
                            request.Address = getUserDetails.Address;
                            request.JoiningDate = DateUtil.GetDateString(getUserDetails.JoiningDate);
                            request.RoleId = getUserDetails.RoleId;
                            request.UserType = getUserDetails.UserType;
                            request.Gender = getUserDetails.Gender;
                            request.Password = getUserDetails.Password;
                            request.ProfilePic = getUserDetails.ProfilePic;
                            if (getUserDetails.UpdatedBy != null)
                            {
                                var updatedUserDetails = await GetUserDetails(getUserDetails.UpdatedBy ?? 0);
                                if (updatedUserDetails != null)
                                {
                                    request.UpdatedBy = getUserDetails.UpdatedBy;
                                    request.UpdatedByName = updatedUserDetails.FirstName + " " + updatedUserDetails.LastName;
                                    request.UpdatedDate = DateUtil.GetDateString(getUserDetails.UpdatedDate);
                                }
                            }
                            else
                            {
                                var createdUserDetails = await GetUserDetails(getUserDetails.UpdatedBy ?? 0);
                                if (createdUserDetails != null)
                                {
                                    request.UpdatedBy = getUserDetails.UpdatedBy;
                                    request.UpdatedByName = createdUserDetails.FirstName + " " + createdUserDetails.LastName;
                                    request.UpdatedDate = DateUtil.GetDateString(getUserDetails.UpdatedDate);
                                }
                            }
                            return PartialView("~/Views/UserDetails/_UserDetailsForm.cshtml", request);
                        }
                        else
                        {
                            response.Acknowledge = Helper.AcknowledgeType.Failure;
                            response.Message = "User details not found";
                        }
                    }
                    else
                    {
                        return PartialView("~/Views/UserDetails/_UserDetailsForm.cshtml", request);
                    }
                }
            }
            catch (Exception ex)
            {
                response.Acknowledge = Helper.AcknowledgeType.Failure;
                response.Message = "Failed to open user details form";
            }
            return Json(response);
        }

        public async Task<IActionResult> SaveUserDetals(CreateUpdateUserDetailRequest request)
        {
            BaseResponse response = new BaseResponse();
            if (request != null)
            {
                try
                {
                    using (var db = new CNJContext())
                    {
                        if (request.Id > 0)
                        {
                            var getUserDetails = db.UserDetails.FirstOrDefault(x => x.Id == request.Id);
                            if (getUserDetails != null)
                            {
                                getUserDetails.OfficeId = request.OfficeId;
                                getUserDetails.FirstName = request.FirstName;
                                getUserDetails.MiddleName = request.MiddleName;
                                getUserDetails.LastName = request.LastName;
                                //getUserDetails.MobileNo = request.MobileNo;
                                getUserDetails.EmailId = request.EmailId;
                                getUserDetails.City = request.City;
                                getUserDetails.Pincode = request.Pincode;
                                getUserDetails.Address = request.Address;
                                getUserDetails.JoiningDate = DateUtil.GetDate(request.JoiningDate);
                                getUserDetails.RoleId = request.RoleId;
                                getUserDetails.UserType = request.UserType;
                                getUserDetails.Gender = request.Gender;
                                getUserDetails.ProfilePic = request.ProfilePic;
                                getUserDetails.UpdatedBy = CurrentUserId;
                                getUserDetails.UpdatedDate = CurrentDate;
                                await db.SaveChangesAsync();
                                response.Acknowledge = Helper.AcknowledgeType.Success;
                                response.Message = "Successfully updated user details";
                            }
                            else
                            {
                                response.Acknowledge = Helper.AcknowledgeType.Failure;
                                response.Message = "User details not found";
                            }
                        }
                        else
                        {

CNJewellerAdmin/Views/UserDetails/Index.cshtml
@{
    int activeStatus = (int)CNJewellerAdmin.Helper.RowStatus.Active;
    int inActiveStatus = (int)CNJewellerAdmin.Helper.RowStatus.Inactive;
}

<div class="row mt-4">
    <div class="col-12">
        <div class="row">
            <div class="col-lg-7">
                <form class="form-inline">
                    <div class="form-group">
                        <h3>User List</h3>
                    </div>
                </form>
            </div>
            <div class="col-lg-5">
                <div class="text-lg-right mt-3 mt-lg-0">
                    <button type="button" id="filterBtn" data-id="0" class="btn btn-success waves-effect waves-light mr-1"><i class="mdi mdi-filter"></i></button>
                    <button type="button" class="btn btn-success waves-effect waves-light mr-1 openUserDetailsForm"><i class="mdi mdi-plus-circle mr-1"></i> Add</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row" style="display:none" id="filterDiv">
    <div class="col-12">
        <div class="card-box mt-3">
            <div class="row">
                <div class="col-lg-8">
                    <h1>hello</h1><br />
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row mt-3">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="header-title"></h4>
                <table id="userDetailsTable" class="table dt-responsive nowrap w-100">
                    <thead>
                        <tr>
                            <th>OfficeName</th>
                            <th>Name</th>
                            <th>Mobile No</th>
                            <th>Email</th>
                            <th>JoiningDate</th>
                            <th>RoleName</th>
                            <th>GenderName</th>
                               <th>City</th>
                            <th>Pincode</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div id="userMasterModel" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <form class="needs-validation" novalidate id="userForm">
                <div id="userMasterDiv">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-success waves-effect waves-light" id="saveUserDetails">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        var userDatatable;
        $(document).ready(function () {

            userDatatable = $("#userDetailsTable").DataTable({
                "ajax": {
                    "url": '@Url.Action("GetUserList","UserDetails")',
                    "type": "GET",
                    "datatype": "json",
                    'data': function (res) {
                        res.officeId = 0;
                    },
                    "dataSrc": "",
                    "responsive": true,
                    "error": function () {
                        alert("Error");
                        //toastr.error("Failed to fetch subscribePlanTypes list", "SubscribePlanTypes");
                    },
                },
                "pageLength": 50,
                "columns": [
                    {
                        "mRender": function (data, type, row) {
                            return '<span class="title">' + row.officeName + '</span>';
                        }
                    },
                    {
                        "mRender": function (data, type, row) {
                            return '<span class="title">' + row.firstName + ' ' + row.middleName + ' ' + row.lastName + '</span>';
                        }
                    },
                    {
                        "mRender": function (data, type, row) {
                        return '<span class="title"><a href="tel:' + row.mobileNo + '">' + row.mobileNo + '</a></span>';
                            //return '<span class="tooltip">Hover over me < span class="tooltiptext" > Tooltip text < /span>< /span>';
                        }
                    },
                    {
                        "mRender": function (data, type, row) {
                            return '<a class="btn waves-effect waves-light" href="mailto:' + row.emailId + '" title="Send Mail" data-plugin="tippy" data-tippy-placement="top">' + row.emailId + '</a>';
                        }
                    },
                    {
                        "mRender": function (data, type, row) {
                            return '<span class="title">' + row.joiningDate + '</span>';
                        }
                    },
                    {
                        "mRender": function (data, type, row) {
                            return '<span class="title">' + row.roleName + '</span>';
                        }
                    },
                    {
                        "mRender": function (data, type, row) {
                            return '<span class="title">' + row.genderName + '</span>';
                        }
                    },
                    {
                        "mRender": function (data, type, row) {
                            return '<span class="title">' + row.city + '</span>';
                        }
                    },
                    {
                        "mRender": function (data, type, row) {
                            return '<span class="title">' + row.pincode + '</span>';
                        }
                    },

                    {
                        "mRender": function (data, type, row) {
                            if (row.rowStatus == @activeStatus) {
                                return '<span class="label label-success pull-right">' + row.rowStatusName + '</span>';
                            }
                            else {
                                return '<span class="label label-danger pull-right">' + row.rowStatusName + '</span>';
                            }
                        }
                    },
                    {
                        "mRender": function (data, type, row) {
                            var htmlContent = '<div class="btn-group mb-2 dropleft">';
							htmlContent += '<div class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fe-more-vertical"></i></div>';
							htmlContent += ' <div class="dropdown-menu">';
                            htmlContent += '<a class="dropdown-item openUserDetailsForm" href="#" data-id=' + row.id + '><i class="fe-edit mr-1"></i>   Edit</a>';
                            htmlContent += '<a class="dropdown-item deleteUsersMaster" href="#" data-id=' + row.id + '><i class="fas fa-trash-alt mr-1"></i>  Delete</a>';
							if (row.rowStatus === @activeStatus) {
								htmlContent += '<a class="dropdown-item updateStatus" href="#" data-id=' + row.id + ' data-statusid="0"><i class="far fa-eye-slash mr-1" ></i>  InActive</a>';
							}
							else {
								htmlContent += '<a class="dropdown-item updateStatus" href="#" data-id=' + row.id + ' data-statusid="1"><i class="far fa-eye mr-1"></i>  Active</a>';
							}
							htmlContent += '</div>';
							htmlContent += '</div>';
							return htmlContent;
                        }
                    }
                ],
                'columnDefs': [{
                    'targets': [0],
                    'className': "capitalize left"
                }, {
                    'targets': [1],
                    'className': "capitalize left"
                },
                {
                    'targets': [2],
                    'className': "capitalize left"
                },
                {
                    'targets': [3],
                    'orderable': true,
                    "width": "10%",
                    'className': "dt-center"
                },
                {
                    'targets': [4],
                    'orderable': false,
                    "width": "10%",
                },
                ],
                'aaSorting': [[1, 'asc']]
            });
        });

        $(document).on('click', '.openUserDetailsForm', function () {
            var id = $(this).attr('data-id');
            $.ajax({
                url: '@Url.Action("OpenUserDetailsForm", "UserDetails")',
                type: 'GET',
                data: { 'id': id },
                dataType: 'html',
                success: function (data) {
                    $("#userMasterDiv").html(data);
                    $("#userMasterModel").modal('show');
                     $(".selecte2Picker").select2();
                    $(".flatpickr").flatpickr({
                       dateFormat:"d/m/Y"
                    });
                },
                error: function (e, v) {
                    alert("error while opening office details form");
                }
            });
        });

        $('#saveUserDetails').on('click', function (e) {
            e.preventDefault();
            if ($("#userForm").parsley().validate()) {
                var request = {
                    Id: $("#hdnUserDetailsId").val(),
                    OfficeId: $("#officeId").val(),
                    FirstName: $("#firstName").val(),
                    MiddleName: $("#middleName").val(),
                    LastName: $("#lastName").val(),
                    MobileNo: $("#mobileNo").val(),
                    EmailId: $("#emailId").val(),
                    City: $("#city").val(),
                    Pincode: $("#pincode").val(),
                    Address: $("#address").val(),
                    JoiningDate: $("#joiningDate").val(),
                    RoleId: $("#roleId").val(),
                    UserType: $("#userType").val(),
                    Gender: $("#gender").val(),
                    Password: $("#password").val(),
                    ProfilePic: $("#profilePic").val()
                }
                $.ajax({
                    url: '@Url.Action("SaveUserDetals", "UserDetails")',
                    type: 'POST',
                    data: { 'request': request },
                    dataType: 'json',
                    success: function (result) {
                        if (result.acknowledge === 1) {
                            showSuccessToast("Save User", result.message);
                            $("#userMasterModel").modal('hide');
                            userDatatable.ajax.reload();
                        }
                        else {
                            showErrorToast("Save User", result.message);
                        }
                    },
                    error: function (e, c) {
                        showErrorToast("Save User", "Failed to save office details");
                    }
                });
            }
        });

        $(document).on('click', '.updateStatus', function () {
            var statusId = $(this).attr('data-statusid');
            var id = $(this).attr('data-id');
            $.ajax({
                url: '@Url.Action("UpdateUserStatus", "UserDetails")',
                type: 'GET',
                data: { 'id': id, 'statusId': statusId },
                dataType: 'json',
                success: function (data) {
                    if (data.acknowledge === 1) {
                        Swal.fire("Success", data.message, "success");
                        userDatatable.ajax.reload();
                    }
                    else {
                        Swal.fire("Failure", data.message, "error");
                    }
                },
            });
        });

        $(document).on('click', '.deleteUsersMaster', function () {
            var Id = $(this).attr("data-id");
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                type: "warning",
                showCancelButton: !0,
                confirmButtonColor: "#3085d6",
                cancelButtonColor: "#d33",
                confirmButtonText: "Yes, delete it!"
            }).then(function (result) {
                if (result.value) {
                    $.ajax({
                        url: '/UserDetails/DeleteUserDetail',
                        type: 'GET',
                        data: { 'id': Id },
                        dataType: 'Json',
                        success: function (result) {
                            if (result.acknowledge === 1) {
                                Swal.fire("Deleted", result.message, "success");
                                userDatatable.ajax.reload();
                            }
                            else {
                                Swal.fire("Failure", result.message, "error");
                            }
                        },
                        error: function (e, v) {
                            Swal.fire("Cancelled", "Cancel  1", "error")
                        }
                    });
                } else if (result.dismiss === "cancel") {
                    Swal.fire("Cancelled", "Cancel 2", "error")
                }
            });
        });


    </script>
}

CNJewellerAdmin/Views/UserDetails/_UserDetailsForm.cshtml
@model CNJewellerAdmin.DTOs.UserDetails.CreateUpdateUserDetailRequest;

<div class="modal-header cusmodelHeader">
    @{
        var headerText = "User";
        if (Model.Id > 0)
        {
            headerText = "Update User Details";
        }
        else
        {
            headerText = "Add User Details";
        }
        <h4 class="modal-title cusmodelTitel">
            @headerText
        </h4>
    }

    <button type="button" class="close cusmodelTitel" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body p-2">
    <div class="row">
        <input type="hidden" asp-for="Id" id="hdnUserDetailsId" />
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Branch Code</label>
                <select asp-for="OfficeId" asp-items="@(new SelectList(Model.Offices,"Id","Name"))" class="form-control selecte2Picker" required data-toggle="select2" id="officeId">
                    <option>Please select one</option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Role</label>
                <select asp-for="RoleId" asp-items="@(new SelectList(Model.Roles,"Id","Name"))" class="form-control" required>
                    <option>Please select one</option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">FirstName</label>
                <input asp-for="FirstName" type="text" class="form-control" id="firstName" placeholder="Please enter first name" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">MiddleName</label>
                <input asp-for="MiddleName" type="text" class="form-control" id="middleName" placeholder="Please enter middle name">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Last Name</label>
                <input asp-for="LastName" type="text" class="form-control" id="lastName" placeholder="Please enter last name" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Mobile No</label>
                <input asp-for="MobileNo" type="text" class="form-control" id="mobileNo" placeholder="Please enter mobile no" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Email</label>
                <input asp-for="EmailId" type="email" class="form-control" id="emailId" placeholder="Please enter email">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Joining Date</label>
                <input asp-for="JoiningDate" type="text" class="form-control flatpickr" id="joiningDate" placeholder="Please enter city" required>
            </div>
        </div>
        @if (Model.Id == 0)
        {
            <div class="col-md-6">
                <div class="form-group">
                    <label for="password" class="control-label">Password</label>
                    <input asp-for="Password" type="password" class="form-control" id="password" placeholder="Please enter city" required>
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="confirmPassword" class="control-label">ConfirmPassword</label>
                    <input asp-for="ConfirmPassword" type="password" class="form-control" id="confirmPassword" placeholder="Please enter city" required>
                    <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                </div>
            </div>
        }
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Gender</label>
                <select asp-for="Gender" asp-items="@(new SelectList(Model.Genders,"Id","Name"))" class="form-control" id="gender">
                    <option>Please select one</option>
                </select>
                <div class="help-block with-errors"></div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">City</label>
                <input asp-for="City" type="text" class="form-control" id="city" placeholder="Please enter city" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Pincode</label>
                <input asp-for="Pincode" type="number" class="form-control" id="pincode" placeholder="Please enter pincode" required>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group">
                <label for="field-3" class="control-label">Address</label>
                <input asp-for="Address" type="text" class="form-control" id="address" placeholder="Please enter description" required>
            </div>
        </div>
    </div>
</div>