CNJewellerAdmin/Models/OfficeMaster.cs
using System;
using System.Collections.Generic;

namespace CNJewellerAdmin.Models
{
    public partial class OfficeMaster
    {
        public OfficeMaster()
        {
            UserDetails = new HashSet<UserDetail>();
        }

        public int Id { get; set; }
        public string OfficeName { get; set; } = null!;
        public string PhoneNo { get; set; } = null!;
        public string Email { get; set; } = null!;
        public string City { get; set; } = null!;
        public string Pincode { get; set; } = null!;
        public string Address { get; set; } = null!;
        public string BranchCode { get; set; } = null!;
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int RowStatus { get; set; }

        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}

CNJewellerAdmin/Controllers/OfficeMasterController.cs
using CNJewellerAdmin.DTOs.Base;
using CNJewellerAdmin.DTOs.UserDetails;
using CNJewellerAdmin.Helper.DateUtil;
using CNJewellerAdmin.Helper;
using CNJewellerAdmin.Models;
using Microsoft.AspNetCore.Mvc;
using CNJewellerAdmin.DTOs.Office;
using Microsoft.EntityFrameworkCore;
using System.Net;
using CNJewellerAdmin.Model;

namespace CNJewellerAdmin.Controllers
{
    public class OfficeMasterController : BaseController
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetOfficeList(int statusId)
        {
            List<OfficeDetailsDTO> result = new List<OfficeDetailsDTO>();
            try
            {
                using (var db = new CNJContext())
                {
                    var userDetails = db.UserDetails.Where(x => x.RowStatus != (int)RowStatus.Deleted);
                    var officeDetails = db.OfficeMasters.Where(x => x.RowStatus != (int)RowStatus.Deleted).Select(x => new OfficeDetailsDTO
                    {
                        Id = x.Id,
                        OfficeName = x.OfficeName,
                        PhoneNo = x.PhoneNo,
                        Email = x.Email,
                        City = x.City,
                        Pincode = x.Pincode,
                        Address = x.Address,
                        BranchCode = x.BranchCode,
                        RowStatus = x.RowStatus
                    });
                    result = officeDetails.ToList();
                }
            }
            catch (Exception ex)
            {
            }
            return Json(result);
        }

        public async Task<IActionResult> OpenOfficeDetailsForm(int id)
        {
            BaseResponse response = new BaseResponse();
            CreateUpdateOfficeMasterRequest request = new CreateUpdateOfficeMasterRequest();
            try
            {
                using (var db = new CNJContext())
                {
                    if (id>0)
                    {
                        var getOfficeDetails = await db.OfficeMasters.FirstOrDefaultAsync(x => x.Id == id && x.RowStatus == (int)RowStatus.Active);
                        if (getOfficeDetails != null)
                        {
                            request.Id = getOfficeDetails.Id;
                            request.OfficeName = getOfficeDetails.OfficeName;
                            request.PhoneNo = getOfficeDetails.PhoneNo;
                            request.Email = getOfficeDetails.Email;
                            request.City = getOfficeDetails.City;
                            request.Pincode = getOfficeDetails.Pincode;
                            request.Address = getOfficeDetails.Address;
                            request.BranchCode = getOfficeDetails.BranchCode;
                            if (getOfficeDetails.UpdatedBy != null)
                            {
                                var updatedUserDetails = await GetUserDetails(getOfficeDetails.UpdatedBy ?? 0);
                                if (updatedUserDetails != null)
                                {
                                    request.UpdatedBy = getOfficeDetails.UpdatedBy;
                                    request.UpdatedByName = updatedUserDetails.FirstName + " " + updatedUserDetails.LastName;
                                    request.UpdatedDate = DateUtil.GetDateString(getOfficeDetails.UpdatedDate);
                                }
                            }
                            else
                            {
                                var createdUserDetails = await GetUserDetails(getOfficeDetails.UpdatedBy ?? 0);
                                if (createdUserDetails != null)
                                {
                                    request.UpdatedBy = getOfficeDetails.UpdatedBy;
                                    request.UpdatedByName = createdUserDetails.FirstName + " " + createdUserDetails.LastName;
                                    request.UpdatedDate = DateUtil.GetDateString(getOfficeDetails.UpdatedDate);
                                }
                            }
                            return PartialView("~/Views/OfficeMaster/_OfficeDetailsForm.cshtml", request);
                        }
                    }
                    else
                    {
                        return PartialView("~/Views/OfficeMaster/_OfficeDetailsForm.cshtml", request);
                    }
                }
            }
            catch (Exception ex)
            {
                response.Acknowledge = Helper.AcknowledgeType.Failure;
                response.Message = "Failed to open office details form";
            }
            return Json(response);
        }

        public async Task<IActionResult> SaveOfficeDetals(CreateUpdateOfficeMasterRequest request)
        {
            BaseResponse response = new BaseResponse();
            if (request != null)
            {
                try
                {
                    using (var db = new CNJContext())
                    {
                        if (request.Id > 0)
                        {
                            var getOfficeDetails = await db.OfficeMasters.FirstOrDefaultAsync(x => x.Id == request.Id);
                            if (getOfficeDetails != null)
                            {
                                getOfficeDetails.OfficeName = request.OfficeName;
                                getOfficeDetails.PhoneNo = request.PhoneNo;
                                getOfficeDetails.Email = request.Email;
                                getOfficeDetails.City = request.City;
                                getOfficeDetails.Pincode = request.Pincode;
                                getOfficeDetails.Address = request.Address;
                                getOfficeDetails.BranchCode = request.BranchCode;
                                getOfficeDetails.UpdatedBy = CurrentUserId;
                                getOfficeDetails.UpdatedDate = CurrentDate;
                                await db.SaveChangesAsync();
                                response.Acknowledge = Helper.AcknowledgeType.Success;
                                response.Message = "Office Updated Succesfully";
                            }
                            else
                            {
                                response.Acknowledge = Helper.AcknowledgeType.Failure;
                                response.Message = "Office details not found";
                            }
                        }
                        else
                        {
                            OfficeMaster officeMaster = new OfficeMaster();
                            officeMaster.OfficeName = request.OfficeName;
                            officeMaster.PhoneNo = request.PhoneNo;
                            officeMaster.Email = request.Email;
                            officeMaster.City = request.City;
                            officeMaster.Pincode = request.Pincode;
                            officeMaster.Address = request.Address;
                            officeMaster.BranchCode = request.BranchCode;
                            officeMaster.CreatedBy = CurrentUserId;
                            officeMaster.CreatedDate = CurrentDate;
                            officeMaster.RowStatus = (int)RowStatus.Active;
                            await db.OfficeMasters.AddAsync(officeMaster);
                            await db.SaveChangesAsync();
                            response.Acknowledge = Helper.AcknowledgeType.Success;
                            response.Message = "New Office Created Succesfully";
                        }
                    }
                }
                catch (Exception ex)
                {
                    response.Acknowledge = Helper.AcknowledgeType.Failure;
                    response.Message = ex.Message;
                }
            }
            else
            {
                response.Acknowledge = Helper.AcknowledgeType.Failure;
                response.Message = "Request is not valid";
            }
            return Json(response);
        }

        public async Task<IActionResult> UpdateOfficeStatus(int id, int statusId)
        {
            BaseResponse response = new BaseResponse();
            try
            {
                using (var db = new CNJContext())
                {
                    var recordStatus = statusId == 1 ? " Activated " : " InActivated ";
                    response = new BaseResponse
                    {
                        Acknowledge = AcknowledgeType.Success,
                        Message = "Office " + recordStatus + " successfully"
                    };
                    var resultData = await db.OfficeMasters.FirstOrDefaultAsync(x => x.Id == id && x.RowStatus != (int)RowStatus.Deleted);
                    if (resultData != null)
                    {
                        resultData.RowStatus = statusId;
                        resultData.UpdatedBy = CurrentUserId;
                        resultData.UpdatedDate = DateUtil.GetCurrentDate();
                        await db.SaveChangesAsync();
                    }
                    else
                    {
                        response.Acknowledge = AcknowledgeType.Failure;
                        response.Message = "Office does not exist";
                    }
                }
            }
            catch (Exception ex)
            {
                response.Acknowledge = (int)AcknowledgeType.Failure;
                response.Message = ex.Message;
            }
            return Json(response);
        }

        public async Task<IActionResult> DeleteOfficeDetail(int id)
        {
            BaseResponse result = new BaseResponse();
            try
            {
                using (var db = new CNJContext())
                {

CNJewellerAdmin/Views/OfficeMaster/Index.cshtml
@{
	int activeStatus = (int)CNJewellerAdmin.Helper.RowStatus.Active;
	int inActiveStatus = (int)CNJewellerAdmin.Helper.RowStatus.Inactive;
}

<div class="row mt-4">
	<div class="col-12">
		<div class="row">
			<div class="col-lg-7">
				<form class="form-inline">
					<div class="form-group">
						<h3>Office Details</h3>
					</div>
				</form>
			</div>
			<div class="col-lg-5">
				<div class="text-lg-right mt-3 mt-lg-0">
												<button type="button" id="filterBtn" data-id="0" class="btn btn-success waves-effect waves-light mr-1"><i class="mdi mdi-filter"></i></button>
								<button type="button" class="btn btn-success waves-effect waves-light mr-1 openOfficeDetailsForm"><i class="mdi mdi-plus-circle mr-1"></i> Add</button>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row" style="display:none" id="filterDiv">
	<div class="col-12">
		<div class="card-box mt-3">
			<div class="row">
				<div class="col-lg-8">
					<h1>hello</h1><br />
				</div>
			</div>
		</div>
	</div>
</div>


<div class="row mt-3">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
				<h4 class="header-title"></h4>
				<table id="officeDetailsTable" class="table dt-responsive nowrap w-100">
					<thead>
						<tr>
							<th>BranchCode</th>
							<th>Name</th>
							<th>PhoneNo</th>
							<th>Email</th>
							<th>City</th>
							<th>Pincode</th>
							<th>Status</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<div id="officeMasterModel" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
	<div class="modal-dialog">
		<div class="modal-content">
			<form class="needs-validation" novalidate id="officeForm">
				<div id="officeMasterDiv">
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-danger waves-effect" data-dismiss="modal">Close</button>
					<button type="button" class="btn btn-success waves-effect waves-light" id="saveOfficeDetails">Save</button>
				</div>
			</form>
		</div>
	</div>
</div>

@section scripts{
    <script type="text/javascript">
		var officeDatatable;
		  $(document).ready(function () {

			officeDatatable = $("#officeDetailsTable").DataTable({
				"ajax": {
					"url": '@Url.Action("GetOfficeList","OfficeMaster")',
					"type": "GET",
					"datatype": "json",
					'data': function (res) {
						res.statusId = 0;
					},
					"dataSrc": "",
					"responsive": true,
					"error": function () {
						alert("Error");
						//toastr.error("Failed to fetch subscribePlanTypes list", "SubscribePlanTypes");
					},
				},
				"pageLength": 50,
				"columns": [
					{
						"mRender": function (data, type, row) {
							return '<span class="title">' + row.branchCode + '</span>';
						}
					},
					{
						"mRender": function (data, type, row) {
							return '<span class="title">' + row.officeName + '</span>';
						}
					},
					{
						"mRender": function (data, type, row) {
							return '<span class="title">' + row.phoneNo + '</span>';
						}
					},
					{
						"mRender": function (data, type, row) {
							return '<span class="title">' + row.email + '</span>';
						}
					},
					{
						"mRender": function (data, type, row) {
							return '<span class="title">' + row.city + '</span>';
						}
					},
					{
						"mRender": function (data, type, row) {
							return '<span class="title">' + row.pincode + '</span>';
						}
					},

					{
						"mRender": function (data, type, row) {
							if (row.rowStatus == @activeStatus) {
								return '<span class="label label-success pull-right">' + row.rowStatusName + '</span>';
							}
							else {
								return '<span class="label label-danger pull-right">' + row.rowStatusName + '</span>';
							}
						}
					},
					{
						"mRender": function (data, type, row) {
							var htmlContent = '<div class="btn-group mb-2 dropleft">';
							htmlContent += '<div class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fe-more-vertical"></i></div>';
							htmlContent += ' <div class="dropdown-menu">';
							htmlContent += '<a class="dropdown-item openOfficeDetailsForm" href="#" data-id=' + row.id + '><i class="fe-edit mr-1"></i>   Edit</a>';
							htmlContent += '<a class="dropdown-item deleteOfficeMaster" href="#" data-id=' + row.id + '><i class="fas fa-trash-alt mr-1"></i>  Delete</a>';
							if (row.rowStatus === @activeStatus) {
								htmlContent += '<a class="dropdown-item updateStatus" href="#" data-id=' + row.id + ' data-statusid="0"><i class="far fa-eye-slash mr-1" ></i>  InActive</a>';
							}
							else {
								htmlContent += '<a class="dropdown-item updateStatus" href="#" data-id=' + row.id + ' data-statusid="1"><i class="far fa-eye mr-1"></i>  Active</a>';
							}
							htmlContent += '</div>';
							htmlContent += '</div>';
							return htmlContent;
						}
					}
				],
				'columnDefs': [{
                    'targets': [0],
                    'className': "capitalize left"
                    },{
                    'targets': [1],
                    'className': "capitalize left"
					},
					{
                    'targets': [2],
                    'className': "capitalize left"
					},
					{
					'targets': [3],
					'orderable': true,
					"width": "10%",
					'className': "dt-center"
				},
				{
					'targets': [4],
					'orderable': false,
					"width": "10%",
				},
			],
				'aaSorting': [[1, 'asc']]
			});
	});

		$(document).on('click', '.openOfficeDetailsForm', function () {
			var id = $(this).attr('data-id');
            $.ajax({
				url: '@Url.Action("OpenOfficeDetailsForm", "OfficeMaster")',
                type: 'GET',
				data: { 'id': id },
                dataType: 'html',
                success: function (data) {
					$("#officeMasterDiv").html(data);
					$("#officeMasterModel").modal('show');
                },
                error: function (e, v) {
                    alert("error while opening office details form");
                }
            });
        });

		$('#saveOfficeDetails').on('click', function (e) {
            e.preventDefault();
			if ($("#officeForm").parsley().validate()) {
             var request = {
				Id: $("#hdnOfficeId").val(),
				OfficeName: $("#officeName").val(),
				PhoneNo: $("#phoneNo").val(),
				Email: $("#email").val(),
				City: $("#city").val(),
				Pincode: $("#pincode").val(),
				Address: $("#address").val(),
				BranchCode: $("#branchCode").val(),
			 }
                $.ajax({
				url: '@Url.Action("SaveOfficeDetals", "OfficeMaster")',
                    type: 'POST',
                    data: { 'request': request },
                    dataType: 'json',
                    success: function (result) {
                        $("#officeMasterModel").modal('hide');
                        if (result.acknowledge === 1) {
						showSuccessToast("Save Office", result.message);
						officeDatatable.ajax.reload();
                        }
                        else {
						showErrorToast("Save Office", result.message);
                        }
                    },
                    error: function (e,c) {
					showErrorToast("Save Office", "Failed to save office details");
                   }
                });
			}
        });

		$(document).on('click', '.updateStatus', function () {
			debugger;
			var statusId = $(this).attr('data-statusid');
            var id = $(this).attr('data-id');
            $.ajax({
				url: '@Url.Action("UpdateOfficeStatus", "OfficeMaster")',
                type: 'GET',
				data: { 'id': id, 'statusId': statusId },
                dataType: 'json',
                success: function (data) {
					if (data.acknowledge === 1) {
						Swal.fire("Success", data.message, "success");
						officeDatatable.ajax.reload();
					}
					else {
						Swal.fire("Failure", data.message, "error");
					}
                },
            });
        });


		$(document).on('click', '.deleteOfficeMaster', function () {
			var Id = $(this).attr("data-id");
			Swal.fire({
				title: "Are you sure?",
				text: "You won't be able to revert this!",
				type: "warning",
				showCancelButton: !0,
				confirmButtonColor: "#3085d6",
				cancelButtonColor: "#d33",
				confirmButtonText: "Yes, delete it!"
			}).then(function (result) {
				if (result.value) {
					$.ajax({
						url: '/OfficeMaster/DeleteOfficeDetail',
						type: 'GET',
						data: { 'id': Id },
						dataType: 'Json',
						success: function (result) {
							if (result.acknowledge === 1) {
								Swal.fire("Deleted", result.message, "success");
								officeDatatable.ajax.reload();
							}
							else {
								Swal.fire("Failure", result.message, "error");
							}
						},
						error: function (e, v) {
							Swal.fire("Cancelled", "Cancel  1", "error")
						}
					});
				} else if (result.dismiss === "cancel") {
					Swal.fire("Cancelled", "Cancel 2", "error")
						}
			});
		});
		</script>}

CNJewellerAdmin/Views/OfficeMaster/_OfficeDetailsForm.cshtml
@model CNJewellerAdmin.DTOs.Office.CreateUpdateOfficeMasterRequest


<div class="modal-header cusmodelHeader">
    @{
        var headerText = "Office";
        if (Model.Id > 0)
        {
            headerText = "Update Office";
        }
        else
        {
            headerText = "Add Office";
        }
        <h4 class="modal-title cusmodelTitel">
            @headerText
        </h4>
    }

    <button type="button" class="close cusmodelTitel" data-dismiss="modal" aria-hidden="true">×</button>
</div>
<div class="modal-body p-2">
    <div class="row">
        <input type="hidden" asp-for="Id" id="hdnOfficeId" />
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Branch Code</label>
                <input asp-for="BranchCode" type="text" class="form-control" id="branchCode" placeholder="Please enter branch code">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Office Name</label>
                <input asp-for="OfficeName" type="text" class="form-control" id="officeName" placeholder="Please enter office name" data-error="Office name is required" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">PhoneNo</label>
                <input asp-for="PhoneNo" type="number" class="form-control" id="phoneNo" placeholder="Please enter phonr no" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Email</label>
                <input asp-for="Email" type="email" class="form-control" id="email" placeholder="Please enter email">
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">City</label>
                <input asp-for="City" type="text" class="form-control" id="city" placeholder="Please enter city" required>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="field-3" class="control-label">Pincode</label>
                <input asp-for="Pincode" type="number" class="form-control" id="pincode" placeholder="Please enter pincode" required>
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group">
                <label for="field-3" class="control-label">Address</label>
                <input asp-for="Address" type="text" class="form-control" id="address" placeholder="Please enter description" required>
            </div>
        </div>
    </div>
</div>